In [1]:
# importing libraries

import pandas as pd
import numpy as np
import os
import sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
# importing Titanic dataset

df_titanic = pd.read_csv(r"C:\\Users\\User\\2_ANN_model_learning_scripts\\0_ANN_tabular_data\\Titanic_dataset.csv")

# printing basic informations such as number of observations and number of features

print(" Number of observations:", df_titanic.shape[0],'\n',"Number of feature:", df_titanic.shape[1],'\n')

# printing top 5 observations

df_titanic.head(5)

 Number of observations: 891
 Number of feature: 12

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# creating a copy of the actual data

df_titanic_relvent = df_titanic.copy()

# dropping un-necessory features

df_titanic_relvent.drop(columns = {'PassengerId', 'Name', 'Ticket', 'Cabin'}, inplace = True)

# changing the dependent variable name

df_titanic_relvent = df_titanic_relvent.rename(columns = {'Survived':'Target'})

# priniting top 5 observations

df_titanic_relvent.head()

   Target  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       0       3    male  22.0      1      0   7.2500        S
1       1       1  female  38.0      1      0  71.2833        C
2       1       3  female  26.0      0      0   7.9250        S
3       1       1  female  35.0      1      0  53.1000        S
4       0       3    male  35.0      0      0   8.0500        S

In [4]:
# categorical treatment - OHE

categorical_cols = ['Pclass', 'Sex', 'Embarked']

for col in categorical_cols:
    df_titanic_relvent = pd.get_dummies(df_titanic_relvent, columns=[col], dtype=int)

# MinMaxScaler on continous variable

continous_cols = ['Age', 'SibSp', 'Fare']

for col in continous_cols:
    df_titanic_relvent[col] = MinMaxScaler().fit_transform(df_titanic_relvent[[col]])

# replacing null values with 0

cols = list(df_titanic_relvent.columns)
cols.remove('Target')

for col in cols:
    df_titanic_relvent[col] = df_titanic_relvent[col].fillna(0)
    
# train test split

X = df_titanic_relvent.drop(columns = 'Target')
y = df_titanic_relvent['Target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 10, shuffle= True)

### perceptron model

In [5]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [6]:
# perceptron uses a single layer, hence we uses a single dense layer only

MLP_model = Sequential([Dense(units = 16, activation= 'relu', name = 'layer1'),
                               Dense(units = 8 , activation= 'relu', name = 'layer2'),
                               Dense(units = 4 , activation= 'relu', name = 'layer3'),
                               Dense(units = 2 , activation= 'relu', name = 'layer4'),
                               Dense(units = 1 , activation= 'sigmoid', name = 'layer5')
                              ])

In [7]:
# model compiling steps: 
# Optimizer - "sgd" (stochastic gradient descent) 
# Loss function - binary_crossentropy 
# metrics  = accuracy

MLP_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [8]:
# Applying the early stopping concept

early_stopping = EarlyStopping(monitor='val_loss',
    patience=50,
    min_delta=0.1,
    restore_best_weights=True,
    verbose=1
)

In [9]:
# fitting the model using train data

MLP_model.fit(X_train, y_train, 
              validation_data= (X_test, y_test), 
              epochs=500, 
              batch_size = 128,
             callbacks=[early_stopping])

Epoch 1/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.3997 - loss: 0.6971 - val_accuracy: 0.4469 - val_loss: 0.6944
Epoch 2/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.4896 - loss: 0.6917 - val_accuracy: 0.6369 - val_loss: 0.6901
Epoch 3/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6538 - loss: 0.6882 - val_accuracy: 0.6592 - val_loss: 0.6864
Epoch 4/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6906 - loss: 0.6831 - val_accuracy: 0.6983 - val_loss: 0.6798
Epoch 5/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6656 - loss: 0.6745 - val_accuracy: 0.7039 - val_loss: 0.6725
Epoch 6/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6686 - loss: 0.6704 - val_accuracy: 0.7207 - val_loss: 0.6654
Epoch 7/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7195 - loss: 0.6589 - val_accuracy: 0.7542 - val_loss: 0.6587
Epoch 8/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7548 - loss: 0.6539 - val_accuracy: 0.7709 - val_loss: 0.6516
Epoch 9/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7630 - loss: 0.6431 - val_accuracy: 0.7709 - val_loss: 0.6439
Epoch 10/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7623 - loss: 0.6354 - val_accuracy: 0.7654 - val_loss: 0.6363
Epoch 11/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7524 - loss: 0.6318 - val_accuracy: 0.7709 - val_loss: 0.6291
Epoch 12/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7602 - loss: 0.6228 - val_accuracy: 0.7933 - val_loss: 0.6222
Epoch 13/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7618 - loss: 0.6068 - val_accuracy: 0.7933 - val_loss: 0.6162
Epoch 14/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7765 - loss: 0.6039 - val_accuracy: 0.7933 - val_loss: 0.6105
Epoch 15/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7813 - loss: 0.5868 - val_accuracy: 0.7877 - val_loss: 0.6054
Epoch 16/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7852 - loss: 0.5851 - val_accuracy: 0.7989 - val_loss: 0.6005
Epoch 17/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7842 - loss: 0.5897 - val_accuracy: 0.8156 - val_loss: 0.5959
Epoch 18/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7947 - loss: 0.5782 - val_accuracy: 0.8212 - val_loss: 0.5920
Epoch 19/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7916 - loss: 0.5903 - val_accuracy: 0.8212 - val_loss: 0.5883
Epoch 20/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8066 - loss: 0.5793 - val_accuracy: 0.8212 - val_loss: 0.5859
Epoch 21/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7963 - loss: 0.5747 - val_accuracy: 0.8212 - val_loss: 0.5841
Epoch 22/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7981 - loss: 0.5610 - val_accuracy: 0.8212 - val_loss: 0.5801
Epoch 23/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7961 - loss: 0.5799 - val_accuracy: 0.8268 - val_loss: 0.5769
Epoch 24/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8036 - loss: 0.5738 - val_accuracy: 0.8212 - val_loss: 0.5751
Epoch 25/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8085 - loss: 0.5697 - val_accuracy: 0.8268 - val_loss: 0.5743
Epoch 26/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8118 - loss: 0.5438 - val_accuracy: 0.8212 - val_loss: 0.5729
Epoch 27/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.7897 - loss: 0.5529 - val_accuracy: 0.8156 - val_loss: 0.5702
Epoch 28/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8085 - loss: 0.5466 - val_accuracy: 0.8156 - val_loss: 0.5679
Epoch 29/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.7924 - loss: 0.5513 - val_accuracy: 0.8156 - val_loss: 0.5666
Epoch 30/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8092 - loss: 0.5643 - val_accuracy: 0.8156 - val_loss: 0.5660
Epoch 31/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8164 - loss: 0.5447 - val_accuracy: 0.8156 - val_loss: 0.5660
Epoch 32/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8053 - loss: 0.5444 - val_accuracy: 0.8156 - val_loss: 0.5652
Epoch 33/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.8028 - loss: 0.5483 - val_accuracy: 0.8156 - val_loss: 0.5626
Epoch 34/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8113 - loss: 0.5450 - val_accuracy: 0.8156 - val_loss: 0.5608
Epoch 35/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8039 - loss: 0.5515 - val_accuracy: 0.8156 - val_loss: 0.5608
Epoch 36/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8164 - loss: 0.5375 - val_accuracy: 0.8156 - val_loss: 0.5604
Epoch 37/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8159 - loss: 0.5448 - val_accuracy: 0.8156 - val_loss: 0.5583
Epoch 38/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8136 - loss: 0.5419 - val_accuracy: 0.8101 - val_loss: 0.5575
Epoch 39/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8088 - loss: 0.5369 - val_accuracy: 0.8101 - val_loss: 0.5569
Epoch 40/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8119 - loss: 0.5430 - val_accuracy: 0.8101 - val_loss: 0.5551
Epoch 41/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8262 - loss: 0.5253 - val_accuracy: 0.8101 - val_loss: 0.5546
Epoch 42/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8178 - loss: 0.5339 - val_accuracy: 0.8101 - val_loss: 0.5539
Epoch 43/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8034 - loss: 0.5378 - val_accuracy: 0.8101 - val_loss: 0.5528
Epoch 44/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8206 - loss: 0.5343 - val_accuracy: 0.8101 - val_loss: 0.5519
Epoch 45/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8406 - loss: 0.5207 - val_accuracy: 0.8101 - val_loss: 0.5512
Epoch 46/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8256 - loss: 0.5348 - val_accuracy: 0.8101 - val_loss: 0.5516
Epoch 47/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8295 - loss: 0.5274 - val_accuracy: 0.8101 - val_loss: 0.5501
Epoch 48/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8080 - loss: 0.5412 - val_accuracy: 0.8101 - val_loss: 0.5488
Epoch 49/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7980 - loss: 0.5298 - val_accuracy: 0.8101 - val_loss: 0.5483
Epoch 50/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8257 - loss: 0.5246 - val_accuracy: 0.8101 - val_loss: 0.5474
Epoch 51/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8155 - loss: 0.5326 - val_accuracy: 0.8101 - val_loss: 0.5456

Epoch 52/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8133 - loss: 0.5256 - val_accuracy: 0.8101 - val_loss: 0.5463
Epoch 53/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8075 - loss: 0.5442 - val_accuracy: 0.8101 - val_loss: 0.5435
Epoch 54/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8027 - loss: 0.5366 - val_accuracy: 0.8101 - val_loss: 0.5428
Epoch 55/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8149 - loss: 0.5259 - val_accuracy: 0.8101 - val_loss: 0.5420
Epoch 56/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8293 - loss: 0.5162 - val_accuracy: 0.8101 - val_loss: 0.5429
Epoch 57/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8277 - loss: 0.5114 - val_accuracy: 0.8101 - val_loss: 0.5407
Epoch 58/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8120 - loss: 0.5234 - val_accuracy: 0.8101 - val_loss: 0.5387
Epoch 59/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8124 - loss: 0.5124 - val_accuracy: 0.8101 - val_loss: 0.5389
Epoch 60/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8120 - loss: 0.5219 - val_accuracy: 0.8101 - val_loss: 0.5372
Epoch 61/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8219 - loss: 0.5079 - val_accuracy: 0.7989 - val_loss: 0.5385
Epoch 62/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8333 - loss: 0.5102 - val_accuracy: 0.8101 - val_loss: 0.5352
Epoch 63/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8118 - loss: 0.5147 - val_accuracy: 0.8045 - val_loss: 0.5366
Epoch 64/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.8023 - loss: 0.5319 - val_accuracy: 0.8045 - val_loss: 0.5349
Epoch 65/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8184 - loss: 0.5099 - val_accuracy: 0.7989 - val_loss: 0.5345
Epoch 66/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8147 - loss: 0.5242 - val_accuracy: 0.8045 - val_loss: 0.5330
Epoch 67/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8087 - loss: 0.5191 - val_accuracy: 0.7989 - val_loss: 0.5346
Epoch 68/500
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8302 - loss: 0.5071 - val_accuracy: 0.7989 - val_loss: 0.5337
Epoch 68: early stopping
Restoring model weights from the end of the best epoch: 18.

In [10]:
# prediction using X_test

y_pred_test = MLP_model.predict(X_test)

# converting observations 1 if prediction is more than 0.5

y_pred_test = (y_pred_test > 0.5).astype(int)

# calculating the accuracy on test data

accuracy_score(y_test, y_pred_test)

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

0.8212290502793296

In [11]:
# to get the model summary

MLP_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                       │ (None, 16)                  │             208 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer2 (Dense)                       │ (None, 8)                   │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer3 (Dense)                       │ (None, 4)                   │              36 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer4 (Dense)                       │ (None, 2)                   │              10 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer5 (Dense)                       │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,181 (4.62 KB)

 Trainable params: 393 (1.54 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 788 (3.08 KB)